services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        value: neondb
      - key: DB_POSTGRESDB_HOST
        value: ep-muddy-star-aoq36b1m.c-2.ap-southeast-1.aws.neon.tech
      - key: DB_POSTGRESDB_PASSWORD
        value: npg_3NilwsyV8rSH
      - key: DB_POSTGRESDB_USER
        value: ep-muddy-star
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: false
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_SSL
        value: true
      - key: N8N_PORT
        value: 5678
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
      - key: WEBHOOK_URL
        value: https://n8n-service.onrender.com/
